kafka:
  brokers:
    - "localhost:9092"
  topic: "my_topic"
  group_id: "my_consumer_group"
  sasl:
    enable: false
    user: ""
    password: ""
  tls:
    enable: false
  version: "2.8.0"

clickhouse:
  hosts:
    - "localhost:9000"
  database: "default"
  table: "my_table"
  username: "default"
  password: "123456"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_life_time: 10m

app:
  batch_size: 1000               # 每批次最大消息数
  flush_interval: 5s              # 最大等待时间
  worker_pool_size: 4             # 并发处理消息的 worker 数
  log_level: "info"